Vasarlas:
  Ko:
    x: 1301
    y: 93
    z: -483
  Vas:
    x: 1299
    y: 93
    z: -483
  Arany:
    x: 1297
    y: 93
    z: -483
Eladas:
  Ko:
    x: 1300
    y: 93
    z: -483
  Vas:
    x: 1298
    y: 93
    z: -483
  Arany:
    x: 1296
    y: 93
    z: -483
